### ISSUE TITLE
make check failed.

### ISSUE THREAD

**Issue by sizeoftank** [pyston/pyston#1247]
I'm work on  ubuntu 16.04 but make check failed.

The following tests FAILED:
      4 - pyston_defaults_tests (Failed)
      5 - pyston_force_llvm_tests (Failed)
      6 - pyston_defaults_cpython (Failed)
Errors while running CTest

**Comment by undingen** [comment]
Looks like all errors are coming from slightly changed error messages in the newer cpython:
```
4: Test command: /usr/bin/python "/home/malloc/pyston/tools/tester.py" "-R" "./pyston" "-j1" "-q" "-k" "-a=-S" "--order-by-mtime" "-t50" "/home/malloc/pyston/test/tests"
4: Test timeout computed to be: 9.99988e+06
4:                             super.py    FAILED (bad output)
4: --- /tmp/expected_dHPWBO	2016-06-12 14:06:46.199532631 +0100
4: +++ /tmp/received_QECO_3	2016-06-12 14:06:46.199532631 +0100
4: @@ -5,7 +5,7 @@
4:  2
4:  C.f()
4:  B.f()
4:  <class '__main__.C'>
4:  'super' object has no attribute 'does_not_exist'
4: -super() argument 1 must be type, not int
4: +must be type, not int
4:  super(type, obj): obj must be an instance or subtype of type
4: 
4:                          imp_test.py    FAILED (bad output)
4: --- /tmp/expected_sLy_Ax	2016-06-12 14:06:46.971533580 +0100
4: +++ /tmp/received_gdC12Q	2016-06-12 14:06:46.971533580 +0100
4: @@ -1,9 +1,9 @@
4:  3
4:  None
4:  myenc
4: -NullImporter() argument 1 must be string, not int
4: +must be string, not int
4:  empty pathname
4:  existing directory
4:  None
4:  False
4:  True
4: 
4:               class_and_func_name.py    FAILED (bad output)
4: --- /tmp/expected_LRjGy7	2016-06-12 14:06:51.919539538 +0100
4: +++ /tmp/received_vcm9Zf	2016-06-12 14:06:51.919539538 +0100
4: @@ -5,11 +5,11 @@
4:  <class 'new_name'>
4:  <type 'exceptions.TypeError'> can't set attributes of built-in/extension type 'int'
4:  int
4:  <type 'exceptions.TypeError'> can only assign string to new_name.__name__, not 'int'
4:  new_name
4: -<type 'exceptions.ValueError'> type name must not contain null characters
4: +<type 'exceptions.ValueError'> __name__ must not contain null bytes
4:  new_name
4:  car
4:  
4:  g
4:  bob
4: 
4:            exceptions_nonreprable.py    FAILED (bad stderr)
4: --- /tmp/expectederr_gaOfIT	2016-06-12 14:07:23.667572722 +0100
4: +++ /tmp/receivederr_zmE4q_	2016-06-12 14:07:23.667572722 +0100
4: @@ -1,4 +1,4 @@
4:  Traceback (most recent call last):
4:    File "/home/malloc/pyston/test/tests/exceptions_nonreprable.py", line 14, in <module>
4:      raise BadException()
4: -__main__.BadException: <exception str() failed>
4: +__main__.BadException
4: 
4/7 Test #4: pyston_defaults_tests ............***Failed   88.97 sec
test 5
    Start 5: pyston_force_llvm_tests

5: Test command: /usr/bin/python "/home/malloc/pyston/tools/tester.py" "-R" "./pyston" "-j1" "-q" "-k" "-a=-S" "-a=-n" "-a=-X" "-t75" "/home/malloc/pyston/test/tests"
5: Test timeout computed to be: 9.99988e+06
5:            exceptions_nonreprable.py    FAILED (bad stderr)
5: --- /tmp/expectederr_Ul4iei	2016-06-12 14:09:37.075626577 +0100
5: +++ /tmp/receivederr_DUhqWB	2016-06-12 14:09:37.075626577 +0100
5: @@ -1,4 +1,4 @@
5:  Traceback (most recent call last):
5:    File "/home/malloc/pyston/test/tests/exceptions_nonreprable.py", line 14, in <module>
5:      raise BadException()
5: -__main__.BadException: <exception str() failed>
5: +__main__.BadException
5: 
```
