### ISSUE TITLE
static assert ubuntu 14.10

### ISSUE THREAD

**Issue by js7222** [pyston/pyston#316]
Hi,

I'm currently getting the following static assert failures when running check-test. Does anyone know what the root cause is?

/home/james/pyston/src/codegen/ast_interpreter.cpp
In file included from /home/james/pyston/src/codegen/ast_interpreter.cpp:36:
In file included from /home/james/pyston/src/runtime/generator.h:19:
/home/james/pyston/src/runtime/types.h:266:1: error: static_assert failed ""
static_assert(offsetof(pyston::BoxedClass, gc_visit) == offsetof(struct _typeobject, _gcvisit_func), "");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/james/pyston/src/runtime/types.h:267:1: error: static_assert failed ""
static_assert(sizeof(pyston::BoxedClass) == sizeof(struct _typeobject), "");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/james/pyston/src/runtime/types.h:269:1: error: static_assert failed ""
static_assert(offsetof(pyston::BoxedHeapClass, as_number) == offsetof(PyHeapTypeObject, as_number), "");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/james/pyston/src/runtime/types.h:270:1: error: static_assert failed ""
static_assert(offsetof(pyston::BoxedHeapClass, as_mapping) == offsetof(PyHeapTypeObject, as_mapping), "");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/james/pyston/src/runtime/types.h:271:1: error: static_assert failed ""
static_assert(offsetof(pyston::BoxedHeapClass, as_sequence) == offsetof(PyHeapTypeObject, as_sequence), "");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/james/pyston/src/runtime/types.h:272:1: error: static_assert failed ""
static_assert(offsetof(pyston::BoxedHeapClass, as_buffer) == offsetof(PyHeapTypeObject, as_buffer), "");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/james/pyston/src/runtime/types.h:273:1: error: static_assert failed ""
static_assert(sizeof(pyston::BoxedHeapClass) == sizeof(PyHeapTypeObject), "");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/james/pyston/src/runtime/types.h:445:1: error: static_assert failed ""
static_assert(sizeof(BoxedDict) == sizeof(PyDictObject), "");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8 errors generated.
[6/115] Building CXX object src/CMakeFiles/PYSTON_OBJECTS.dir/codegen/stackmaps.cpp.o
ninja: build stopped: subcommand failed.

**Comment by undingen** [comment]
with the following changes the code should build with the g++ 4.9 stdlibc++:
inside ```from_cpython/Include/dictobject.h```
- change ```char _filler[48];``` to ```char _filler[48+8];```

inside ```from_cpython/Include/object.h```
- change ```char _dep_getattrs[56];``` to ```char _dep_getattrs[56+8];```

Problem is that we currently don't have a configure script which could insert the correct number depending on the c++ library container sizes.

**Comment by js7222** [comment]
Thanks I managed to find out the same thing. What is it specifically in stdlibc++ that has changed size?

**Comment by dagar** [comment]
I'm working on a cmake configure script to get the sizeof pyston::BoxedDict in PR #436.

**Comment by dagar** [comment]
This should be resolved now.
